### ISSUE TITLE
googletest version conflicts

### ISSUE THREAD

**Issue by pinventado** [kevinwortman/tuffix#10]
The script currently installs ```libgtest-dev``` that conflicts with the compiled version of ```googletest```.

I think if we remove the line below, it should resolve the issue.

https://github.com/kevinwortman/tuffix/blob/8514855b892cb6c29784ac3fe10ef25daa59d0d4/tuffix.yml#L168

**Comment by kevinwortman** [comment]
This was resolved in fd0c0b082d0bffa758091330ff9580a5e5015116.
