### ISSUE TITLE
Document virtualization BIOS settings

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/tuffix#14]
Hernan Manabat writes

> I ran into few instances where users have problem running Tuffix VM because of the CPU Virtualization being disabled by default on some systems.  Users need to restart their machine and must go into the BIOS and enable this feature first in order such issue.  Perhaps you can mention something like that in your Tuffix VM document's FAQ section.

We should add an item about this to the installation instructions in the VM section.

**Comment by mshafae** [comment]
I addressed this in the VM Instructions pull request I just made.
