### ISSUE TITLE
Deactivate upgrade notices

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/tuffix#15]
We instruct students to ignore messages about upgrading packages or releases. But it would be simpler to just turn off those messages. There's an option to do that in the packages settings dialog.

**Comment by pinventado** [comment]
I've had students who clicked upgrade despite the constant reminders I give them not to do so. I think this is a better way to handle this

**Comment by kevinwortman** [comment]
We should also tell them to turn off the upgrade notices in VirtualBox.

**Comment by mshafae** [comment]
Is this even a problem on a native install? If this is only to address VirtualBox VMs breaking, then this is another reason to not use VMs. Shutting off the notifier can be rolled into the tuffixize process.
https://askubuntu.com/questions/218755/how-to-disable-the-update-manager-popup

**Comment by puhfessorp** [comment]
Personally, I've been extracting the VDI from the OVA and having them hook it into a brand new VM. Ends up working with any version of VirtualBox.

If they then want to copy/paste or share folders between the host/guest, I direct them to instructions for installing Guest Additions themselves.

**Comment by kevinwortman** [comment]
@mshafae Yes, the reason why they shouldn't upgrade packages in the VM is that changing the kernel version breaks the VM Guest Additions, students who opt for the VM are generally not equipped to fix that, and I don't think we have support resources to help them with it.

I agree that the more elegant solution is to insist on native installs. @puhfessorp that's a creative solution, but I have to wonder, if students are sophisticated enough to do that process, why they don't just do a native install. The VM option only exists so newcomers can have a plug-and-play experience and not experience stereotype threat.

IMO, the next time we build a VM (if that ever happens) we should follow the instructions in @mshafae 's link to deinstall update-manager.
