### ISSUE TITLE
Migrate to NixOS for reproducibility and simplicity

### ISSUE THREAD

**Issue by diamondburned** [kevinwortman/tuffix#33]
Hello. I am an incoming freshman in the class of Fall 2020. As the class has its own Linux distro that is Ubuntu-based, I think will help a lot. However, some issues, such as #13, bring up the problems of using a script to bootstrap a distro that is Ubuntu based. This issue will go over some of those disadvantages and how Nix will solve them.

### Reproducibility

This distro seems to be bootstrapped using a shell script. A bootstrap shell script is either stateless or stateful.

A stateless script is not aware of the system state: it installs everything from scratch, and if there are modifications to certain configuration files, the script will apply it anyway and potentially break the system. 

A stateful script is slightly better: it is aware of previous modifications, either from its own script or from the state of the system. A stateful script that is aware of enough state will eventually cover all cases. However, it is impractical to cover all cases, which leads us to simplicity.

### Simplicitly

Scripts in general have a flaw: they require imperative lines of code executed sequentially that would require the developer to explicitly declare each possible scenario as well as ways to handle them. This is not only time-consuming to develop, it also needlessly bloats up the code.

It could be argued that the 80/20 rule may apply: we could cover 80% of the cases with 20% of the code that we would otherwise have to write/read. However, Nix fixes this in a very elegant way that I will be going into later.

### What is Nix?

Wikipedia states that "NixOS is a Linux distribution built on top of the Nix package manager. It uses declarative configuration and allows reliable system upgrades."

It also states that "Nix is a cross-platform package manager that utilizes a purely functional deployment model where software is installed into unique directories generated through cryptographic hashes."

### What does that mean?

First, let's go over declarative configuration. Let's look at the first 7 packages required for the Fall 2020 class:

- a2ps
- autoconf
- automake
- build-essential
- chromium-browser
- cimg-dev
- clang

Here's the same package, except in Nix's declarative configuration format.

```nix
{ config, pkgs, ... }: {
    # GNU build tools are covered by Nix in its nix-shell derivative, which I will
    # go over below.
    environment.systemPackages = with pkgs; [ a2ps chromium-browser cimg clang ];
}
```

There's one difference to the code above: instead of writing a script that executes `apt install <pkgs...>`, all the packages needed are now written inside a config file that one could so easily install by just importing the file into their system:

```nix
{ config, pkgs, ... }: {
    imports = [ ./class-pkgs.nix ];
}
```

To solve the problems of potentially overriding configuration files, Nix users simply configure their system using the declarative Nix syntax instead of writing a different configuration file for each application/service. This not only simplifies the job by miles, but it would also organize the configuration files in an organized and consistent manner.

### What else can we do?

Let's look at how we decided to set the wallpaper. The instructions in the Markdown file writes:

> Use Firefox to download a background image, move it to to ~/Pictures, set it as the desktop wallpaper, delete ~/.mozilla

Here's how wallpapers are changed on NixOS GNOME:

```nix
{ config, pkgs, ... }:

# Fetch the Tuffnix repository, which would have the wallpaper in its Git
# repository.
let tuffnix = builtins.fetchGit {
    url = "https://github.com/somebody/tuffnix.git";
    rev = "0d05c53204da3b576f810ef2e1312b19bf2420b7";
    sha256 = "1lc26jkjfw1cridymic82lk3zdwhlccs7s5mhkdnz7cbcwllyy54";
};

in {
    # Use the GNOME 3 desktop environment, similar to Ubuntu.
    services.xserver = {
        displayManager.gdm.enable = true;
        desktopManager.gnome3.enable = true;
    };


    # Here we have the user-specific configurations for "student".
    home-manager.users.student = {
        # GNOME wallpapers are stored inside dconf, so we change that.
        dconf.settings = {
            "org/gnome/desktop/background" = {
                # Use the wallpaper in the Git repository.
                picture-uri = "${tuffnix}/background.jpg";
            };
        };
    };
}
```

As we can see above, Nix not only automates this without any human interactions, it also does this cleanly and *declaratively*.

#### Bonus: the Nix shell

Nix provides a `nix-shell` command which drops the user into a fresh shell instance with additional things installed. This does not globally install anything, which makes it very convenient for development. Here is an example of a `nix-shell` that brings `go` (the Golang compiler) into the current shell:

```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation rec {
    name = "myproject";
    buildInputs = with pkgs; [ go ];
}
```

This file would be written into `shell.nix`. To enter the shell with those packages inside, one only needs to run `nix-shell shell.nix`.

### How does Nix solve the 2 issues above?

The above snippets of code demonstrates a fraction of what Nix could do best: it is a language and package manager that allows expressing system configurations in a simple and declarative manner. What should have been a shell script that would need to run commands and hope that nothing is broken is replaced with a straightforward and declarative configuration file.

A specific example of reproducibility would be the `rev` Git hash and `sha256` output hash provided in `builtins.fetchGit`. This tells Git that the repository downloaded must be of a certain commit hash and must give an output that matches the given hash. Because of this, all successful outputs of `tuffnix` will always be the same.

Git repositories aren't the only thing that is hashed. Every single thing managed by Nix will have a reproducible output hash that those things must satisfy. Nix calls this a "derivative". All output derivatives are immutable, meaning they cannot be changed without the hashes being changed as well.

### How would NixOS be deployed to students' computers?

That is a great question. This is one of the possible drawbacks in using NixOS over as basic of a distro as Ubuntu: there is no way for graphical installation. NixOS has to be installed in the terminal. It requires manual partitioning before any of the automatic commands could work.

Thankfully, since Nix is reproducible and declarative, it provides tools to both generate a disk image in ISO form as well as virtual manager images with the given Nix configuration files. In fact, one can easily generate a disk image of their own desktop with just a few extra lines AND their system configurations would still be usable.

### Nix is a source-based distro with a build cache.

Nix derivatives have to be created from certain pieces of code, so most of what Nix has in its repository are build instructions and configuration declarations. Because of this, Nix is treated as a source-based distro.

However, Nix also has a build cache. Thanks to Nix's reproducible features, all builds always have hashes attached to them, meaning they are immutable for that piece of configuration, making it very easy to distribute Nix builds safely and quickly.

One could also either [self-host a binary cache][self-host-binary-cache] or [distribute public build derivatives][cachix] for others to use. This is extremely useful when it comes to distributing Nix configuration files, as those who install the configurations can expect everything to be downloaded as binaries and nothing to be built.

[self-host-binary-cache]: https://nixos.wiki/wiki/Binary_Cache
[cachix]: https://cachix.org/

## Conclusion

NixOS can reliably help students as well as others bootstrap their setup. Doing so is a lot better than using a shell script to bootstrap packages and configuration files onto a (hopefully fresh) Ubuntu setup. If done properly, disk images could even be generated that would install everything right during the installation process without any further effort.

## Additional tidbits

Tidbits that aren't organized in any specific order of any meaning but is still important enough to be mentioned.

### Nix is both rolling release and standard release

The Nix package manager defaults to using a standard release channel (repository) that behaves similarly to Ubuntu's release system. However, Nix users could also opt for the `unstable` channel, which is rolling. This is extremely useful for those who need the cutting edge packages.

Nix also allows a configuration to use multiple Nix package repositories (nixpkgs) at once. If a use case requires a cutting edge version of `clang` that isn't available in stable yet, one could always just use the `clang` of a newer channel while leaving the rest in tact.

### Nix's channel versions can be locked

If extreme reproducibility is needed, one could lock their nixpkgs onto a certain commit. This is extremely easy because nixpkgs itself is just [a Git repository][nixpkgs]. As Nix always have build instructions, one could always reliably get the packages as long as the source code is available.

[nixpkgs]: https://github.com/NixOS/nixpkgs

### Dependency hell is not a problem on Nix

Nix allows keeping multiple versions of packages on the same system. As each version has a different output hash, Nix doesn't really care about them colliding. Packages that rely on different versions of a dependency will happily coexist.

In the case that a package needs an outdated dependency, as long as the source code is available, Nix can always build that dependency without colliding with anything else.

### Nix allows rolling back after each configuration change

Nix creates a "generation" for each configuration rebuild. Although rebuilds will straight up fail if any part of the configuration is erroneous, even if the error somehow slips through, one can always simply reboot to the last generation.

### Nix Overlays allow for easy override of packages

While other distros would require rebuilding a package from bare source code if certain changes were to be made (such as patches or cutting edge upgrades), Nix allows overriding existing build instructions. The below code overrides package `libhandy`'s version:

```nix
{ config, pkgs, ... }: {
    nixpkgs.overlays = [
        (self: super: {
            libhandy = super.libhandy.overrideAttrs(old: {
                name = "libhandy-0.90.0";
                src  = builtins.fetchGit {
                    url = "https://gitlab.gnome.org/GNOME/libhandy.git";
                    rev = "c7aaf6f4f50b64ee55fcfee84000e9525fc5f93a";
                };
            });
        })
    ];
}
```

### Nix works on MacOS as well

Nix can work natively on MacOS thanks to [Nix Darwin][nix-darwin]. Although certain things may not work, other things like services, packages and user configurations would still work.

[nix-darwin]: https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/

### Nixpkgs is the second largest package repository ever

According to [Repology][repology], nixpkgs contains 51481 packages, which is only behind the Arch User Repository (AUR) at 55557 packages. It is worth mentioning that this number of packages does not make Nix any less stable, unlike the AUR.

[repology]: https://repology.org/

## Reference

- NixOS manual: https://nixos.org/nixos/manual/
- Nixpkgs manual: https://nixos.org/nixpkgs/manual/
- Uses and applications: https://nixos.wiki/wiki/Applications

**Comment by diamondburned** [comment]
It seems like Tuffix actually uses Ansible to deploy. Ansible has almost the same flaws as shell scripts do, such as potentially breaking the system by overriding configuration files. It is also not built-in, which makes it relatively harder to use.

**Comment by einrol** [comment]
Seriously? The only solution you see is migrating the entire system to a new fancy thing? A "thing" that no one involved in the project understands? If that wasn't enough, NixOS is infamous for it's documentation, or lack thereof.

**Comment by diamondburned** [comment]
> The only solution you see is migrating the entire system to a new fancy thing?

I don't see where I wrote that it is the only solution.

> A "thing" that no one involved in the project understands?

I did explain quite a few points about the system.

> If that wasn't enough, NixOS is infamous for it's documentation, or lack thereof.

I'm not sure how this is the case either.

Why the hostile comment?

**Comment by kevinwortman** [comment]
Let's please be civil.

Thank you for your interest and for taking the time to do this. However, this suggestion is not compatible with the purpose of this project. Please introduce yourself in the slack workspace and learn about the requirements for this software. The whole point is to provide a definitive build platform on an annual release cycle. Rolling releases would undermine that.
