### ISSUE TITLE
Tuffix 2020 Edition doesn't work for MacBook Pro

### ISSUE THREAD

**Issue by tevinvu** [kevinwortman/tuffix#45]
hi, I am trying to install Tuffix 2020 for my MacOS Mojave. After import the Tuffix 2020 Edition.ovf, hit Continue button and it got hang while reading applicance 'User/.../Tuffix 2020 Edition.ovf'. I have checked your suggestion and the file ovf is fully download. Please advise. Thanks
![Screen Shot 2021-02-19 at 8 18 31 PM](https://user-images.githubusercontent.com/12075982/108583686-39100200-72f0-11eb-8e86-8bd44f47a9cd.png)

**Comment by kevinwortman** [comment]
This is a request for support, so as stated in the instructions, you should ask this question in the #general channel of the slack workspace at https://csuf-tuffix.slack.com/ .
