### ISSUE TITLE
Consider moving the detailed installation instructions to the project Wiki

### ISSUE THREAD

**Issue by MagicFab** [kevinwortman/tuffix#5]
Detailed installation instructions are on Google Drive, most probably on someones personal account which risks disappearing overtime.
It can't be modified or improved by external contributors either, as it's read-only.
Please consider enabling or opening access to the project's wiki and moving the document to it under a Free license so others can also contribute.

**Comment by kevinwortman** [comment]
This is a mostly internal project intended only for students and faculty at CSU Fullerton. Are you affiliated with CSUF? The Drive solution seems to work fine for people with a CSUF account.

**Comment by MagicFab** [comment]
Other schools and teachers could benefit from this work and contribute to improve it. I am not affiliated with CSUF. My concern is the Google Drive information will be lost at some point, it can be preserved and maintained better here, on the project wiki.

**Comment by kevinwortman** [comment]
I took your suggestion to our internal mailing list, and the consensus is that **yes**, going forward we should move our documentation onto the public GitHub platforms. Fair warning, we probably won't have a chance to move on this until the start of our next semester in January-February.

**Comment by kevinwortman** [comment]
These instructions have been moved into markdown documents in this github repo.

**Comment by MagicFab** [comment]
Thank you!
