### ISSUE TITLE
Missing script to verify installation was successful

### ISSUE THREAD

**Issue by CreativeTechGuy** [kevinwortman/tuffix#6]
After following the "Native Installation" instructions to install Tuffix on a clean Linux install, there should be a script that can be run to verify that everything was successfully installed and configured.

Given the fact that the concept behind Tuffix is to ensure that all users are running identical machines, there should be some way to ensure that this is true. Scripts or installs can fail, versions might differ, or other odd issues might occur.

I'd suggest a secondary test script which would go through and run a set of scripts to verify that everything that was supposed to be installed is working correctly. And maybe even throw in a few scripts which should fail given that Tuffix doesn't include certain packages.

**Comment by kevinwortman** [comment]
Thanks for the input. Ansible already gives us something like this for free; you can run the playbook whenever you want, and if your system has been fully "Tuffixized," nothing happens. So right now the check is to rerun the playbook and see whether it does anything. Does that meet your need or are you envisioning something more elaborate?

**Comment by CreativeTechGuy** [comment]
That's what I found out after I posted the issue.

* My only other thoughts were to check for additional software which would conflict with the software which Tuffix installs. For example if someone installs Tuffix on Ubuntu vs Xubuntu.
* Or checking/ensuring versions of specific software since Ansible installs the newest version which matches the package name.

My whole idea/concern is probably not necessary, I just felt uneasy due to the fact that I couldn't be sure that the custom installed system was identical.

I was envisioning the case where I had custom installed Tuffix and later ran into the issue where something worked on my machine but not on the professor's. Either because I installed it at a later date than they did and so I have a slightly newer version of a package or something became mis-configured through use. I was just thinking it could be nice to have a script you can run before you turn in an assignment to sanity check the state of your machine to prove the system integrity. Then if there was a dispute later, you could reference that integrity check which showed the system met Tuffix's criteria at the time of submission.

You can probably close this issue though as this edge case is probably unlikely. I just wanted to propose the idea.

**Comment by kevinwortman** [comment]
OK thanks. I guess if someday you find that a more elaborate validation script seems necessary, you can open a new issue or reopen this one.
