### ISSUE TITLE
g++ defaults to GCC 8 not GCC 9

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/tuffix#9]
Thomas Bettens observes

> One thing I noticed: while GCC 9 is installed, the default still points to GCC 8.  
> 
> g++ -v
> 
> gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)
> 
> /usr/bin/g++ points to /usr/bin/g++-8. Should it point to /usr/bin/g++-9?  
> 
> g++-9  -v 
> 
> gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2-19.04)
> 
> Likely an alternative setting/update somewhere ...

**Comment by mshafae** [comment]
This isn't a problem on Ubuntu 19.10 or later since GCC 9 is the default.

**Comment by kevinwortman** [comment]
Thanks, I'll close this since we've moved to a later Ubuntu version.
